name: medhub_application
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.2.3
  go_router: ^14.2.6
  fluttertoast: ^8.2.8
  intl: ^0.19.0
  mockito: ^5.4.4
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_medhub.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Overpass
      fonts:
        - asset: assets/fonts/Overpass-Regular.ttf
    - family: Overpass-Bold
      fonts:
        - asset: assets/fonts/Overpass-Bold.ttf
    - family: Overpass-ExtraBold
      fonts:
        - asset: assets/fonts/Overpass-ExtraBold.ttf
    - family: Sofia-Pro
      fonts:
        - asset: assets/fonts/Sofia-Pro-Regular.otf
    - family: Sofia-Pro-Bold
      fonts:
        - asset: assets/fonts/Sofia-Pro-Bold.otf
